// import {inter} from 'next/font/google'
import Mno from '@/compont/Mno';


// const inter=inter({subsets:['latin']})

export const metadata={
  title:'create Next App',
  description:'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Mno/>
        {children}

      </body>

    </html>
  )
}



// 'use client'
// import './globals.css'
// import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body >
//         {children}
//         <ProgressBar
//           heignt='4px'
//           // color='red'
//           options={{ showSpinner: false }}

//         />

//       </body>

//     </html>
//   )
// }
